twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        notifs: '@App\Services\NotificationsServices'
when@test:
    twig:
        strict_variables: true
